# Generated by Django 5.0.8 on 2025-04-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=250)),
                ('kort', models.TextField()),
                ('fordel', models.TextField()),
                ('ulemp', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Django',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('beskriv', models.TextField()),
                ('link_app', models.CharField(max_length=50)),
                ('link', models.URLField(blank=True)),
                ('login', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Python',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('beskriv', models.TextField()),
                ('link_app', models.CharField(max_length=50)),
                ('link', models.URLField(blank=True)),
                ('login', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Small',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('foto', models.ImageField(blank=True, upload_to='staticfiles/images/')),
            ],
        ),
    ]
